### PR TITLE
chore(dependencies): update dependencies

### LINKED ISSUE #72: Update yarn packages (Aug 2022)
Many of our packages are now a major version behind - we should try to get on the latest versions of all of them

```bash
➜  hub git:(main) yarn outdated

Package                          Current Wanted  Latest Package Type    URL
@noble/ed25519                   1.6.0   1.6.1   1.6.1  dependencies    https://paulmillr.com/noble/
@types/faker                     5.5.9   5.5.9   6.6.9  devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/faker
@types/jest                      27.5.2  27.5.2  28.1.7 devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jest
@types/node                      17.0.45 17.0.45 18.7.6 devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node
@typescript-eslint/eslint-plugin 5.30.0  5.33.1  5.33.1 devDependencies https://github.com/typescript-eslint/typescript-eslint#readme
@typescript-eslint/parser        5.30.0  5.33.1  5.33.1 devDependencies https://github.com/typescript-eslint/typescript-eslint#readme
eslint                           8.18.0  8.22.0  8.22.0 devDependencies https://eslint.org
ethereum-cryptography            1.1.0   1.1.2   1.1.2  dependencies    https://github.com/ethereum/js-ethereum-cryptography#readme
faker                            5.5.3   5.5.3   6.6.6  dependencies    https://github.com/Marak/Faker.js#readme
husky                            7.0.4   7.0.4   8.0.1  devDependencies https://typicode.github.io/husky
jest                             27.5.1  27.5.1  28.1.3 devDependencies https://jestjs.io/
lint-staged                      12.5.0  12.5.0  13.0.3 devDependencies https://github.com/okonet/lint-staged#readme
log-update                       4.0.0   4.0.0   5.0.1  dependencies    https://github.com/sindresorhus/log-update#readme
neverthrow                       4.3.1   4.4.2   5.0.0  dependencies    https://github.com/supermacro/neverthrow#readme
nodemon                          2.0.18  2.0.19  2.0.19 devDependencies https://nodemon.io
ts-jest                          27.1.5  27.1.5  28.0.8 devDependencies https://kulshekhar.github.io/ts-jest
ts-node                          10.8.1  10.9.1  10.9.1 devDependencies https://typestrong.org/ts-node
```

### PR DESCRIPTION
**Pull request by shrimalmadhur**
update dependencies of yarn packages

## Motivation

Update the node dependencies
Fixed #72 

## Change Summary
Update `package.json`

Describe the changes being made in 1-2 concise sentences.

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [x] The title of this PR adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [x] The PR has been tagged with the appropriate change type label(s) (i.e. documentation, feature, bugfix, or chore)
- [ ] Changes to the protocol specification have been merged

## Additional Context

If this is a relatively large or complex change, provide more details here that will help reviewers

### CODE REVIEW

**Comment by varunsrin** [comment]
thanks for the pr! 

@shrimalmadhur you'll need to [sign your commits](https://github.com/farcasterxyz/hub/blob/main/CONTRIBUTING.md#12-signing-commits) to be able to merge in

**Comment by varunsrin** [comment]
also don't worry about faker, see: https://stackoverflow.com/questions/70597019/what-happened-with-faker-js

**Comment by shrimalmadhur** [comment]
> thanks for the pr!
> 
> @shrimalmadhur you'll need to [sign your commits](https://github.com/farcasterxyz/hub/blob/main/CONTRIBUTING.md#12-signing-commits) to be able to merge in

Oof. I thought I have been signing commit be default. will sign it and update

**Comment by varunsrin** [comment]
for faker, you may need to switch from the old package (faker) to the new community owned one (faker-js), since the old one was effectively nuked.

https://github.com/faker-js/faker

**Comment by shrimalmadhur** [comment]
> for faker, you may need to switch from the old package (faker) to the new community owned one (faker-js), since the old one was effectively nuked.
> 
> https://github.com/faker-js/faker

Yep. I actually changed that but I think that was a bit more involved change so I think separate PR would make sense for it.

**Comment by shrimalmadhur** [comment]
Closing this due to some signing issue in previous commit. New PR #89

**Pull request closed without merging**
